/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
}

group = "com.gec"
version = "0.0.1-SNAPSHOT"
description = "lab2"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.jar{
	manifest{
	attributes["Main-Class"] = "com.gec.lab2.App"
     }
	duplicatesStrategy=DuplicatesStrategy.EXCLUDE

	from({
	  configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
	 })
}
